import sys, json

data = json.load(sys.stdin)
docs = data['data']['docs']
for doc in docs:
    proved = doc.get('identificationProved', {})
    print('=== RAPPORT ID:', doc['_id'], '===')
    print('Annee:', doc.get('annee'))
    print()
    print('--- identificationProved ---')
    print('provinceAdministrative:', proved.get('provinceAdministrative'))
    print('provinceEducationnelle:', proved.get('provinceEducationnelle'))
    print('nombreTerritoires:', proved.get('nombreTerritoires'))
    print('nombreSousDivisions:', proved.get('nombreSousDivisions'))
    print('directeurProvincial:', proved.get('directeurProvincial'))
    print()
    pers = doc.get('personnel', {})
    pa = pers.get('personnelAdministratif', {})
    sd = pa.get('sousDivision', {})
    print('--- personnel.personnelAdministratif.sousDivision ---')
    print('hommes:', sd.get('hommes'))
    print('femmes:', sd.get('femmes'))
    print()
    gouv = doc.get('gouvernance', {})
    rem = gouv.get('remunerationPersonnel', {})
    sd_rem = rem.get('sousDivision', {})
    print('--- gouvernance.remunerationPersonnel.sousDivision ---')
    print('totalAgents:', sd_rem.get('totalAgents'))
    print('nonPayes:', sd_rem.get('nonPayes'))
    print()
    infra = gouv.get('infrastructureBureaux', {})
    sd_infra = infra.get('sousDivision', {})
    print('--- gouvernance.infrastructureBureaux.sousDivision ---')
    print('proprietaire:', sd_infra.get('proprietaire'))
    print('locataire:', sd_infra.get('locataire'))
    print()
